---
title: "postgres_test"
author: "Chengxi"
date: "2025-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("DBI")
install.packages("RPostgres")
install.packages("RSQLite")
```

```{r}
library(DBI)
library(RPostgres)
library(RSQLite)
library(dplyr)
library(mgcv)
```


# use to load the data to db
```{r}
sqlite_con <- dbConnect(RSQLite::SQLite(), "D:/R_studio_working_dir/DATA3888_group/Global_Coral_Bleaching_Database_SQLite_11_24_21.db")
```

# Must connect and disconect after use
```{r}
con <- dbConnect(
  RPostgres::Postgres(),
  dbname = "Data3888_Global_Coral_Bleaching_Database",
  host = "localhost",
  port = 5432,
  user = "postgres",
  password = "magic123"
)
```

# write data into db

```{r}
# List SQLite tables
tables <- dbListTables(sqlite_con)

# For each table, read from SQLite and write to PostgreSQL
for (tbl in tables) {
  data <- dbReadTable(sqlite_con, tbl)
  dbWriteTable(con, tbl, data, overwrite = TRUE)
}
```

# list all the colname from the database

```{r}
for (tbl in tables) {
  cat("Table:", tbl, "\n")
  cols <- dbListFields(sqlite_con, tbl)
  print(cols)
  cat("\n")
}
```

# list first 5 row data from Query_6_Sites_with_Multiple_Sample_Events

```{r}
cmd <- "SELECT * FROM \"Query_6_Sites_with_Multiple_Sample_Events\" LIMIT 5"
result <- dbGetQuery(con, cmd)
result
```

```{r}
dbListTables(con)
```


```{r}
sql <- "
SELECT 
  se.\"Date_Year\"    AS Year,
  e.\"SSTA_DHWMean\"  AS DHW,
  b.\"Bleaching_Prevalence_Score\" AS BleachScore
FROM \"Sample_Event_tbl\"    AS se
JOIN \"Environmental_tbl\"   AS e  
  ON se.\"Sample_ID\" = e.\"Sample_ID\"
JOIN \"Bleaching_tbl\"       AS b  
  ON se.\"Sample_ID\" = b.\"Sample_ID\"
WHERE e.\"SSTA_DHWMean\" IS NOT NULL
  AND b.\"Bleaching_Prevalence_Score\" IS NOT NULL;
"

raw <- dbGetQuery(con, sql)

raw
```


```{r}
head(raw)
summary(raw)
anyNA(raw)
```

```{r}
yearly <- raw %>%
  group_by(year) %>%
  summarise(
    mean_DHW       = mean(dhw, na.rm = TRUE),
    mean_BleachPct = mean(bleachscore, na.rm = TRUE),
    n_samples      = n()
  ) %>%
  ungroup()

print(yearly)
```

```{r}
gam_mod <- gam(
  mean_BleachPct ~ s(year, k = 10) + s(mean_DHW, k = 10),
  data   = yearly,
  family = gaussian()
)

summary(gam_mod)

plot(gam_mod, shade = TRUE, pages = 1)
```



# Must Disconnect

```{r}

dbDisconnect(sqlite_con)
dbDisconnect(con)
```

